import type { Metadata } from "next";
import "@/scss/universal.scss";
import { mainFont, secondaryFont } from "@/public/utils/fonts";


export const metadata: Metadata = {
  title: "Dev Adarsh - Tech versatile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mainFont.className} ${secondaryFont.variable}`}>{children}</body>
    </html>
  );
}
